url = https://sampleapp.tricentis.com/101/index.php
autoLinkText = Automobile
makeDDId = make
epName = [kW]
domCss = input[placeholder='MM/DD/YYYY']
seatsXpath = /html/body/div[1]/div/div[1]/div/div/form/div/section[1]/div[4]/select